version: '3.8'

services:
  app:
    build: .
    container_name: tyche-backend
    restart: unless-stopped
    ports:
      - "5005:5005"
      - "6379:6379" 
    environment:
      # Application environment variables
      PORT: 5005
      NODE_ENV: development
      REDIS_URL: redis://localhost:6379
    env_file:
      - .env
    networks:
      - tyche-network

networks:
  tyche-network:
    driver: bridge