name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v3
      with:
        repository: muffafa/tyche-beta
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Add upstream repository
      run: git remote add upstream https://github.com/usetyche/tyche-beta.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes into fork
      run: git merge upstream/main --allow-unrelated-histories

    - name: Push changes to fork
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
